#!/bin/bash
#
# This file is sourced by other scripts, so you can customize this file
# and still run the steps according to your preferences.
#
REPO="https://github.com/barabo/fhir-to-omop-demo"
FILE="demo/vars"

# For scripts that use concurrency, this is a default setting for
# the number of parallel operations.
CONCURRENCY=$(( $( getconf _NPROCESSORS_ONLN ) - 1 ))
(( CONCURRENCY < 1 )) && CONCURRENCY=1

# Determine the current directory.
THIS_DIR="$( realpath "$( dirname "${0}" )" )"
# Override THIS_DIR if vars was sourced from the command-line.
[[ "${0}" == "${SHELL}" ]] && THIS_DIR="${PWD}"
REPO_DIR="${THIS_DIR%%/fhir-to-omop-demo*}/fhir-to-omop-demo"
DEMO_DIR="${REPO_DIR}/demo"

# A central place where large amounts of data can be put.
# This could be on a larger or faster volume, if wanted.
DATA_DIR="${REPO_DIR}/data"
EXPORT_DIR="${DATA_DIR}/bulk-export"
IMPORT_DIR="${DATA_DIR}/coherent/fhir"

# These locations are used for translation.
FHIR_IN="${EXPORT_DIR}/fhir"
OMOP_OUT="${DATA_DIR}/omop"

# This is the cdm.db that we're loading data into.
CDM_DB="${DATA_DIR}/cdm.db"

# This is where you should put your downloaded and extracted Athena files.
TERMINOLOGY_DIR="${DATA_DIR}/athena"

# FHIR server variables.
FHIR_PORT=8080
FHIR_SERVER="http://localhost:${FHIR_PORT}"
FHIR_BASE="${FHIR_SERVER}/fhir"

# Set this to true or false to enable or disable running docker as root.
# You shouldn't have to, but I've found on some systems where you have
# recently set up docker this is required.
SUDO_DOCKER="false"

# OMOPCDM DDL files
DDL_DIR="${DEMO_DIR}/omopcdm/ddl/5.4/sqlite_extended"

# FHIR_JQ settings
FHIR_JQ_REPO="$( realpath "${REPO_DIR}/../fhir-jq" )"
if ! [[ -d "${FHIR_JQ_REPO}" ]]; then
  if cd "${REPO_DIR}/../" &>/dev/null; then
    echo "Attempting to clone fhir-jq into ${PWD}..."
    gh repo clone barabo/fhir-jq
    cd - &>/dev/null
  fi
  echo "Please clone barabo/fhir-jq and set FHIR_JQ_REPO in ${REPO_DIR}/demo/vars"
else

  FHIR_JQ="${FHIR_JQ_REPO}/module"
  FHIR_JQ_BIN="${FHIR_JQ_REPO}/fhir-jq/bin"

  # Export these for fhir-jq, which needs them.
  export FHIR_JQ
  export PATH="${PATH}:${FHIR_JQ_BIN}"
fi
