#!/bin/bash
#
# Converts FHIR Patient resources to OMOPCDM person records.
#
source _common.sh

REPO="https://github.com/barabo/fhir-to-omop-demo"
FILE="data/convert/mapping/004-Patient-person.sh"

simple_map '
#--------------------------#-----------------------------#-----------------------#
# FHIR Patient             # OMOP person                 # Notes                 #
#--------------------------#-----------------------------#-----------------------#
  null,                    # person_id                   #
  null,                    # gender_concept_id           #
  null,                    # year_of_birth               #
  null,                    # month_of_birth              #
  null,                    # day_of_birth                #
  null,                    # birth_datetime              #
  null,                    # race_concept_id             #
  null,                    # ethnicity_concept_id        #
  null,                    # location_id                 #
  null,                    # provider_id                 #
  null,                    # care_site_id                #
  null,                    # person_source_value         #
  null,                    # gender_source_value         #
  null,                    # gender_source_concept_id    #
  null,                    # race_source_value           #
  null,                    # race_source_concept_id      #
  null,                    # ethnicity_source_value      #
  null,                    # ethnicity_source_concept_id #
#--------------------------#-----------------------------#-----------------------#
'

exit 0

cat <<NOTES  # Everything below is notes.

# Terminology search:
https://athena.ohdsi.org/search-terms/terms

# OMOP CDM 5.4 person TABLE
https://ohdsi.github.io/CommonDataModel/cdm54.html#person
CREATE TABLE person (
  person_id integer NOT NULL PRIMARY KEY,
  gender_concept_id integer NOT NULL REFERENCES CONCEPT (CONCEPT_ID),
  year_of_birth integer NOT NULL,
  month_of_birth integer NULL,
  day_of_birth integer NULL,
  birth_datetime datetime NULL,
  race_concept_id integer NOT NULL REFERENCES CONCEPT (CONCEPT_ID),
  ethnicity_concept_id integer NOT NULL REFERENCES CONCEPT (CONCEPT_ID),
  location_id integer NULL REFERENCES LOCATION (LOCATION_ID),
  provider_id integer NULL REFERENCES PROVIDER (PROVIDER_ID),
  care_site_id integer NULL REFERENCES CARE_SITE (CARE_SITE_ID),
  person_source_value TEXT NULL,
  gender_source_value TEXT NULL,
  gender_source_concept_id integer NULL REFERENCES CONCEPT (CONCEPT_ID),
  race_source_value TEXT NULL,
  race_source_concept_id integer NULL REFERENCES CONCEPT (CONCEPT_ID),
  ethnicity_source_value TEXT NULL,
  ethnicity_source_concept_id integer NULL REFERENCES CONCEPT (CONCEPT_ID)
);

# FHIR R4 Example Patient Resource
https://www.hl7.org/fhir/R4B/Patient.html
{
  "resourceType": "Patient",
  "id": "1538705",
  "meta": {
    "versionId": "1",
    "lastUpdated": "2024-06-01T20:48:08.103+00:00",
    "source": "#JwSlTQNM9ozMNs45",
    "profile": [
      "http://hl7.org/fhir/us/core/StructureDefinition/us-core-patient"
    ]
  },
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">Generated by <a href=\"https://github.com/synthetichealth/synthea\">Synthea</a>.Version identifier: v2.6.1-174-g66c40fa7\n .   Person seed: 6724970922987631132  Population seed: 1626964256551</div>"
  },
  "extension": [
    {
      "url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-race",
      "extension": [
        {
          "url": "ombCategory",
          "valueCoding": {
            "system": "urn:oid:2.16.840.1.113883.6.238",
            "code": "2106-3",
            "display": "White"
          }
        },
        {
          "url": "text",
          "valueString": "White"
        }
      ]
    },
    {
      "url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-ethnicity",
      "extension": [
        {
          "url": "ombCategory",
          "valueCoding": {
            "system": "urn:oid:2.16.840.1.113883.6.238",
            "code": "2186-5",
            "display": "Non Hispanic or Latino"
          }
        },
        {
          "url": "text",
          "valueString": "Non Hispanic or Latino"
        }
      ]
    },
    {
      "url": "http://hl7.org/fhir/StructureDefinition/patient-mothersMaidenName",
      "valueString": "Jettie913 Goyette777"
    },
    {
      "url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-birthsex",
      "valueCode": "M"
    },
    {
      "url": "http://hl7.org/fhir/StructureDefinition/patient-birthPlace",
      "valueAddress": {
        "city": "Adams",
        "state": "Massachusetts",
        "country": "US"
      }
    },
    {
      "url": "http://synthetichealth.github.io/synthea/disability-adjusted-life-years",
      "valueDecimal": 0.3206087251858809
    },
    {
      "url": "http://synthetichealth.github.io/synthea/quality-adjusted-life-years",
      "valueDecimal": 61.67939127481412
    }
  ],
  "identifier": [
    {
      "system": "https://github.com/synthetichealth/synthea",
      "value": "7b68ef38-85c5-3f4f-ae44-e5bb70b52962"
    },
    {
      "type": {
        "coding": [
          {
            "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
            "code": "MR",
            "display": "Medical Record Number"
          }
        ],
        "text": "Medical Record Number"
      },
      "system": "http://hospital.smarthealthit.org",
      "value": "7b68ef38-85c5-3f4f-ae44-e5bb70b52962"
    },
    {
      "type": {
        "coding": [
          {
            "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
            "code": "SS",
            "display": "Social Security Number"
          }
        ],
        "text": "Social Security Number"
      },
      "system": "http://hl7.org/fhir/sid/us-ssn",
      "value": "999-47-1518"
    },
    {
      "type": {
        "coding": [
          {
            "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
            "code": "DL",
            "display": "Driver's License"
          }
        ],
        "text": "Driver's License"
      },
      "system": "urn:oid:2.16.840.1.113883.4.3.25",
      "value": "S99913965"
    },
    {
      "type": {
        "coding": [
          {
            "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
            "code": "PPN",
            "display": "Passport Number"
          }
        ],
        "text": "Passport Number"
      },
      "system": "http://standardhealthrecord.org/fhir/StructureDefinition/passportNumber",
      "value": "X13610202X"
    }
  ],
  "name": [
    {
      "use": "official",
      "family": "Murazik203",
      "given": [
        "Irving123"
      ],
      "prefix": [
        "Mr."
      ]
    }
  ],
  "telecom": [
    {
      "system": "phone",
      "value": "555-706-6086",
      "use": "home"
    }
  ],
  "gender": "male",
  "birthDate": "1924-09-23",
  "deceasedDateTime": "1987-05-21T23:48:11-04:00",
  "address": [
    {
      "extension": [
        {
          "url": "http://hl7.org/fhir/StructureDefinition/geolocation",
          "extension": [
            {
              "url": "latitude",
              "valueDecimal": 42.4550110506162
            },
            {
              "url": "longitude",
              "valueDecimal": -71.27850130606157
            }
          ]
        }
      ],
      "line": [
        "181 Waters Viaduct"
      ],
      "city": "Lexington",
      "state": "MA",
      "postalCode": "02420",
      "country": "US"
    }
  ],
  "maritalStatus": {
    "coding": [
      {
        "system": "http://terminology.hl7.org/CodeSystem/v3-MaritalStatus",
        "code": "M",
        "display": "M"
      }
    ],
    "text": "M"
  },
  "multipleBirthBoolean": false,
  "communication": [
    {
      "language": {
        "coding": [
          {
            "system": "urn:ietf:bcp:47",
            "code": "en-US",
            "display": "English"
          }
        ],
        "text": "English"
      }
    }
  ]
}

NOTES
